### ISSUE TITLE
User page fails to navigate except on refresh

### ISSUE THREAD

**Issue by AndrewRayCode** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#42]
Loading the home page and then clicking on users is blocked:
```
Failed to load http://localhost:3003/example/users: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:3000' is therefore not allowed access.
```

It looks like the [`transform_url` function in react-website](https://github.com/catamphetamine/react-website/blob/d4aac1777c526781ec4ae48288f31ea813a31139/source/HttpClient.js#L49) mangles the `/api/example/users` into the raw api call port (why?). 

I like the pattern of proxying `/api` to the private API server, which is also what the now deprecated [`react-redux-universal-hot-example` project does](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/server.js#L36-L39), but it seems like you hard coded the comment for why you made the changes [in](https://github.com/catamphetamine/webpack-react-redux-server-side-render-example/blob/master/proxy-server/index.js#L13-L16) [5](https://github.com/catamphetamine/webpack-react-redux-server-side-render-example/blob/master/rendering-service/main.js#L10-L14) [separate](https://github.com/catamphetamine/webpack-react-redux-server-side-render-example/blob/master/src/configuration.js#L4-L13) [files](https://github.com/catamphetamine/webpack-react-redux-server-side-render-example/blob/master/src/react-website.js#L69-L79) [,](https://github.com/catamphetamine/webpack-react-redux-server-side-render-example/blob/master/webpack/devserver.js#L11-L20), but unless i'm missing something, you could have simply added `Access-Control-Allow-Origin: *` to the api server to allow for cross-origin requests? I don't believe it's "Chrome" specifically disallowing this behavior it's part of the [CORS standard](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

I think it's also fine to proxy `/api` down into an internal API server in production, if you don't need to scale up a separate API. your comment implies you only made this change to work around the cors issue.

**Comment by catamphetamine** [comment]
I see.
So you really dug deep...
Into the dark corners where outdated comments live, camelCase is not used and such.

The error you described doesn't happen to me, see the screenshot.

The reason that I recently introduced `transformURL` in this example project is because I personally moved on from proxying to querying the API directly (e.g. "serverless", AWS lambda and such).
Feels more modern, more hi-tech.
The proxying is only left for `localhost` which is not allowed to be CORSed in Chrome.
https://stackoverflow.com/a/10892392/970769
So it looks messy indeed. Still, there's no other way around other than "Use Firefox" approach.

The api server does return the appropriate header:

![image](https://user-images.githubusercontent.com/477167/46627355-e8464700-cb42-11e8-850b-c755602512e4.png)
